FROM eclipse-temurin:17-jdk AS build

RUN mkdir -p /app
WORKDIR /app

# Cache getting dependencies through Maven Wrapper
COPY .mvn /app/.mvn
COPY mvnw .
COPY mvnw.cmd .
COPY pom.xml .
RUN ./mvnw dependency:go-offline

# Copy code and build into .jar
COPY . /app
RUN ./mvnw install

FROM eclipse-temurin:17-jre AS run

# Copy .jar from other container
RUN mkdir -p /app
WORKDIR /app
COPY --from=build /app/target/*.jar /app/run.jar

CMD ["java", "-jar", "run.jar"]
