#!/bin/bash

commit_hash=$(git rev-parse HEAD)
date=$(date -u +%F)
export TAG=${date}.${commit_hash}

docker_compose_files=(docker-compose/docker-compose.*.prod.yml)
as_arguments=$(printf " -f %s" "${docker_compose_files[@]}")

docker-compose $as_arguments build --pull