#!/bin/bash

docker_compose_files=(docker-compose/docker-compose.*.${1}.yml)
as_arguments=$(printf " -f %s" "${docker_compose_files[@]}")

exec 5>&1
output=$(docker-compose $as_arguments up --build | tee >(cat - >&5))

failed_services=$(echo "${output}" | grep "exited with code" | grep -v "exited with code 0")
failed_services_count=$(echo "${failed_services}" | wc -l)

if [ $failed_services_count -ne 0 ]; then
    printf "\n\n${failed_services}"
    exit 1
fi