#!/bin/bash

docker_compose_files=(docker-compose/docker-compose.*.${1}.yml)
as_arguments=$(printf " -f %s" "${docker_compose_files[@]}")

exec 5>&1
output=$(docker-compose $as_arguments up --build | tee >(cat - >&5))

did_fail=$(echo "${output}" | grep "exited with code" | grep -v "exited with code 0" | wc -l)

exit ${did_fail}