version: '3.9'

services:
  comic_store:
    build: 
      context: ../services/comic_store
      dockerfile: Dockerfile.dev
    volumes:
      - ../services/comic_store:/app
    ports:
      - 8080:8080