version: '3.0'

services:

  localstack:
    image: localstack/localstack:latest
    environment: 
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=s3
      - DATA_DIR=/tmp/comics/
    ports:
      - '4566:4566'
    volumes:
      - ./stubs/s3:/tmp/comics/
      - "/var/run/docker.sock:/var/run/docker.sock"