version: '3.9'

services:
  frontend: 
    build:
      context: '../services/frontend'
      dockerfile: 'Dockerfile.prod'
    ports:
      - 3000:3000
  comic_store:
    build: 
      context: '../services/comic_store'
      dockerfile: 'Dockerfile.prod'
    ports:
      - 8080:8080