FROM node:16-alpine

RUN mkdir -p /app
WORKDIR /app

# Cache getting dependencies through NPM
COPY package.json /app
COPY package-lock.json /app
RUN npm ci

ENV NODE_ENV development

CMD ["npm", "run", "dev"]