FROM node:18-alpine

RUN mkdir -p /app
WORKDIR /app

# Cache getting dependencies through NPM
COPY package.json /app
COPY package-lock.json /app
RUN npm ci --legacy-peer-deps

COPY . /app

CMD ["npm", "test"]
