FROM node:18-alpine

RUN mkdir -p /app
WORKDIR /app

# Cache getting dependencies through NPM
COPY package.json /app
COPY package-lock.json /app
RUN npm ci --legacy-peer-deps

ENV NODE_ENV development

CMD ["npm", "run", "dev"]
