FROM node:18-alpine

RUN mkdir -p /app
WORKDIR /app

# Cache getting dependencies through NPM
COPY package.json /app
COPY package-lock.json /app
RUN npm ci --legacy-peer-deps

ENV NODE_ENV production

# Copy code and build
COPY . /app
RUN npm run build

CMD ["npm", "start"]
