name: ci

on:
  push:
    branches: [ master ]
  workflow_dispatch: # Allows running this workflow manually from the Actions tab
jobs:  
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: ./run test
      - name: Build
        run: ./build
      - name: Publish Images
        run: echo '[TODO] Publish the built images to a docker registry'
      - name: Deploy
        run: echo '[TODO] Deploy the published images'
      - name: Verify Deployment
        run: echo '[TODO] Verify that the deployment was successful'
      - name: Verify Application
        run: echo '[TODO] Verify that the app is behaving correctly'
