name: test-and-build

on:
  pull_request:
    branches: [ master ]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: ./run test
      - name: Build
        run: ./build